# Generated by Django 4.2.2 on 2024-07-15 19:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Member",
            new_name="Member123",
        ),
    ]
