# Generated by Django 4.2.2 on 2024-07-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0002_rename_member_member123"),
    ]

    operations = [
        migrations.AddField(
            model_name="member123",
            name="joined_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="member123",
            name="phone",
            field=models.IntegerField(null=True),
        ),
    ]
