# Generated by Django 4.2.2 on 2024-07-16 18:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0003_member123_joined_date_member123_phone"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Member123",
            new_name="Mymember",
        ),
    ]
